name: Draft Release

on:
  push:
    branches:
      - next

permissions:
  contents: write # to create releases

jobs:
  draft_release:
    if: startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0 # we need the tags and the commit history for the gh release create command

      - name: Extract release version
        run: |
          RELEASE_VERSION=$(jq -r '.version' package.json)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          PREVIOUS_VERSION=$(git describe --tags --abbrev=0)
          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV

      - name: Release Args - Prerelease
        if: contains(github.event.head_commit.message, '-')
        run: |
          RELEASE_ARGS="--prerelease"
          echo "RELEASE_ARGS=$RELEASE_ARGS" >> $GITHUB_ENV

      - name: Release Args - Release
        if: "!contains(github.event.head_commit.message, '-')"
        run: |
          RELEASE_ARGS="--latest"
          echo "RELEASE_ARGS=$RELEASE_ARGS" >> $GITHUB_ENV

      - name: Create draft release
        run: |
          gh release create \
            v$RELEASE_VERSION \
            --draft \
            $RELEASE_ARGS \
            --generate-notes \
            --notes-start-tag $PREVIOUS_VERSION \
            --title v$RELEASE_VERSION
        env:
          GH_TOKEN: ${{ github.token }}
