name: Preflight Comment

on:
  workflow_run:
    workflows: 'PR'
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment-code-generation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: 'Comment Code Generation'
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: 'next'

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set node version to 22
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Transpile ts
        run: pnpm tsup-node .github/workflows/commentCodeGeneration.ts --format cjs --clean false --out-dir .github/workflows

      - name: Comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { script } = require('${{ github.workspace }}/.github/workflows/commentCodeGeneration.cjs')
            await script(github, context, ${{ github.event.workflow_run.conclusion == 'success' }})
